export const act3 = {
  scene5_drift: {
    id: "scene5_drift",
    lines: [
      { text: "The content changes.", pauseAfter: 1100 },
      { text: "Then changes again.", pauseAfter: 1100 },
      { text: "", pauseAfter: 900 },
      { text: "You stop remembering what you just watched.", pauseAfter: 1400 },
      { text: "", pauseAfter: 1000 },
      { text: "Your thumb moves before you think.", pauseAfter: 1300 },
      { text: "", pauseAfter: 900 },
      { text: "It almost feels calming.", pauseAfter: 1200 },
      { text: "Not having to choose anything.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Stay in the loop", effects: { time_loss: 3 }, next: "scene6_awareness" },
      { text: "Slow down slightly", effects: { awareness: 1 }, next: "scene6_awareness" },
      { text: "Keep searching for something better", effects: { time_loss: 2 }, next: "scene6_awareness" },
      { text: "Try to stop thinking", effects: { tension: 1 }, next: "scene6_awareness" },
    ],
  },
  scene5_reflect: {
    id: "scene5_reflect",
    lines: [
      { text: "Something feels wrong.", pauseAfter: 1300 },
      { text: "", pauseAfter: 900 },
      { text: "Not dangerous.", pauseAfter: 1000 },
      { text: "Not dramatic.", pauseAfter: 1000 },
      { text: "", pauseAfter: 900 },
      { text: "Just… empty.", pauseAfter: 1400 },
      { text: "", pauseAfter: 900 },
      { text: "Like time passed without asking you first.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Look away from the screen", effects: { awareness: 2 }, next: "scene6_awareness" },
      { text: "Return to the feed", effects: { time_loss: 2 }, next: "scene6_awareness" },
      { text: "Sit with the feeling", effects: { resistance: 2 }, next: "scene6_awareness" },
      { text: "Distract yourself again", effects: { time_loss: 2 }, next: "scene6_awareness" },
    ],
  },
  scene6_awareness: {
    id: "scene6_awareness",
    lines: [
      { text: "It doesn’t feel like long.", pauseAfter: 1000 },
      { text: "But it is.", pauseAfter: 1100 },
      { text: "", pauseAfter: 800 },
      { text: "Minutes blur together.", pauseAfter: 1100 },
      { text: "Or maybe longer.", pauseAfter: 1000 },
      { text: "", pauseAfter: 800 },
      { text: "You weren’t counting.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Keep scrolling", effects: { time_loss: 3 }, next: "scene7" },
      { text: "Check the time", effects: { awareness: 1 }, next: "scene7" },
      { text: "Switch to something else", effects: { time_loss: 2 }, next: "scene7" },
      { text: "Pause for a second", effects: { awareness: 1 }, next: "scene7" },
    ],
  },
  scene7: {
    id: "scene7",
    lines: [
      { text: "You hesitate.", pauseAfter: 1000 },
      { text: "Just for a second.", pauseAfter: 900 },
      { text: "", pauseAfter: 800 },
      { text: "Something feels… off.", pauseAfter: 1100 },
      { text: "Like you’ve been here longer than you meant to.", pauseAfter: 1200 },
      { text: "", pauseAfter: 800 },
      { text: "But you’re already mid-scroll.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Ignore it", effects: { time_loss: 3 }, next: "scene8" },
      { text: "Try to remember why you opened it", effects: { awareness: 2 }, next: "scene8" },
      { text: "Keep going anyway", effects: { time_loss: 3 }, next: "scene8" },
      { text: "Slow down", effects: { resistance: 1 }, next: "scene8" },
    ],
  },
  scene8: {
    id: "scene8",
    lines: [
      { text: "You notice the loop now.", pauseAfter: 1100 },
      { text: "The way one thing leads to another.", pauseAfter: 1200 },
      { text: "", pauseAfter: 900 },
      { text: "It’s not random.", pauseAfter: 1000 },
      { text: "It keeps you here.", pauseAfter: 1100 },
      { text: "", pauseAfter: 900 },
      { text: "Knowing that…", pauseAfter: 1000 },
      { text: "doesn’t stop it.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Keep scrolling", effects: { time_loss: 3 }, next: "scene9" },
      { text: "Try to stop", effects: { resistance: 3 }, next: "scene9" },
      { text: "Just one more", effects: { time_loss: 2 }, next: "scene9" },
      { text: "Put the phone down", effects: { awareness: 2 }, next: "scene9" },
    ],
  },
  scene9: {
    id: "scene9",
    lines: [
      { text: "You tell yourself it’s fine.", pauseAfter: 900 },
      { text: "Everyone does this.", pauseAfter: 1000 },
      { text: "", pauseAfter: 800 },
      { text: "It’s just a break.", pauseAfter: 1000 },
      { text: "Just a moment.", pauseAfter: 1000 },
      { text: "", pauseAfter: 800 },
      { text: "But it hasn’t been a moment.", pauseAfter: 1100 },
      { text: "Not for a while.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Continue", effects: { time_loss: 3 }, next: "scene10" },
      { text: "Stop now", effects: { resistance: 3 }, next: "scene10" },
      { text: "Think about why", effects: { awareness: 2 }, next: "scene10" },
      { text: "Just one more minute", effects: { time_loss: 2 }, next: "scene10" },
    ],
  },
  scene10: {
    id: "scene10",
    lines: [
      { text: "This is the moment.", pauseAfter: 1100 },
      { text: "You could stop here.", pauseAfter: 1200 },
      { text: "", pauseAfter: 900 },
      { text: "Or not.", pauseAfter: 1000 },
      { text: "", pauseAfter: 900 },
      { text: "It doesn’t feel like a big decision.", pauseAfter: 1100 },
      { text: "But it is.", pauseAfter: 0 },
    ],
    choices: [
      { text: "Keep going", effects: { time_loss: 3 }, next: "ending" },
      { text: "Stop", effects: { resistance: 3 }, next: "ending" },
      { text: "Pause", effects: { awareness: 2 }, next: "ending" },
      { text: "Ignore the thought", effects: { tension: 2 }, next: "ending" },
    ],
  },
};
